# Generated by Django 3.0.4 on 2020-04-16 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=25)),
                ('middle_name', models.CharField(blank=True, default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('street', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=25)),
                ('pin', models.IntegerField(default=0)),
                ('designation', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_rpm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='machine_maintenance_report',
            fields=[
                ('store_name', models.CharField(default='', max_length=40)),
                ('total_cost', models.FloatField()),
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('maintenance_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(default='', max_length=35)),
                ('gst_number', models.CharField(default='', max_length=15)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.employee')),
            ],
        ),
        migrations.CreateModel(
            name='yarn',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_bags', models.IntegerField()),
                ('gate_pass_number', models.IntegerField()),
                ('weight', models.FloatField()),
                ('party_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.party')),
            ],
        ),
        migrations.CreateModel(
            name='wages_report',
            fields=[
                ('bill_number', models.AutoField(primary_key=True, serialize=False)),
                ('salary_date', models.DateField(blank=True, default=datetime.date.today)),
                ('number_of_days', models.IntegerField()),
                ('salary', models.FloatField()),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.employee')),
            ],
        ),
        migrations.CreateModel(
            name='party_bill_delivery',
            fields=[
                ('slip_number', models.AutoField(primary_key=True, serialize=False)),
                ('gst_number', models.CharField(default='', max_length=15)),
                ('total_meter_received', models.FloatField()),
                ('total_meter_delivered', models.FloatField()),
                ('peak', models.CharField(default='', max_length=25)),
                ('bill_date', models.DateField(blank=True, default=datetime.date.today)),
                ('party_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.party')),
            ],
        ),
        migrations.CreateModel(
            name='design',
            fields=[
                ('design_id', models.AutoField(primary_key=True, serialize=False)),
                ('peak', models.CharField(default='', max_length=25)),
                ('cost', models.FloatField()),
                ('colors', models.CharField(default='', max_length=25)),
                ('party_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.party')),
            ],
        ),
        migrations.CreateModel(
            name='beam_inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_number', models.IntegerField()),
                ('total_meter', models.IntegerField()),
                ('party_id', models.CharField(max_length=30)),
                ('warp_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'unique_together': {('beam_number', 'warp_date')},
            },
        ),
        migrations.CreateModel(
            name='maintenance_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(default='', max_length=25)),
                ('quantity', models.IntegerField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.machine_maintenance_report')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.machine')),
            ],
            options={
                'unique_together': {('machine_id', 'part_name', 'bill_id')},
            },
        ),
        migrations.CreateModel(
            name='machine_operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('machine_electricity_consumption', models.FloatField()),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.employee')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.machine')),
            ],
            options={
                'unique_together': {('machine_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='bill_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=30)),
                ('bill_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textmanage.wages_report')),
            ],
            options={
                'unique_together': {('bill_number', 'item')},
            },
        ),
    ]
