# Generated by Django 3.0.5 on 2020-04-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam_inward',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.party'),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.wages_report'),
        ),
        migrations.AlterField(
            model_name='design',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.party'),
        ),
        migrations.AlterField(
            model_name='machine_operator',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.employee'),
        ),
        migrations.AlterField(
            model_name='party',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.employee'),
        ),
        migrations.AlterField(
            model_name='party_bill_delivery',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.party'),
        ),
        migrations.AlterField(
            model_name='wages_report',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.employee'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textmanage.party'),
        ),
    ]
