# Generated by Django 3.0.5 on 2020-04-29 13:50

import datetime
import django.core.validators
from django.db import migrations, models
import textmanage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('textmanage', '0002_auto_20200417_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$', 'Invalid Phone Number')]),
        ),
        migrations.AlterField(
            model_name='beam_inward',
            name='warp_date',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[textmanage.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Name cannot contain digits')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Name cannot contain digits')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Name cannot contain digits')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Invalid Pin Code')]),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_rpm',
            field=models.IntegerField(validators=[textmanage.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='machine_maintenance_report',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[textmanage.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='machine_maintenance_report',
            name='maintenance_date',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[textmanage.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='machine_operator',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[textmanage.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='party',
            name='gst_number',
            field=models.CharField(default='', max_length=15, validators=[textmanage.validators.get_gstin_with_check_digit]),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(default='', max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Name cannot contain digits')]),
        ),
        migrations.AlterField(
            model_name='party_bill_delivery',
            name='bill_date',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[textmanage.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='party_bill_delivery',
            name='gst_number',
            field=models.CharField(default='', max_length=15, validators=[textmanage.validators.get_gstin_with_check_digit]),
        ),
        migrations.AlterField(
            model_name='wages_report',
            name='salary_date',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[textmanage.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='gate_pass_number',
            field=models.IntegerField(validators=[textmanage.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='number_of_bags',
            field=models.IntegerField(validators=[textmanage.validators.nonneg]),
        ),
    ]
